volumes:
  data:

services:
  full_stack_dev:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password123
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql